# zsh Options
setopt EXTENDED_HISTORY       # record timestamp of command in HISTFILE
setopt HIST_IGNORE_ALL_DUPS   # ignore duplicated commands history list
setopt HIST_EXPIRE_DUPS_FIRST # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt HIST_IGNORE_SPACE      # ignore commands that start with space

# Contains path to DOTFILES repo
[ -f "$HOME/.env.sh" ] && source "$HOME/.env.sh"

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in $DOTFILES/zsh/{path,bash_prompt,exports,aliases,functions,extra}.sh; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file"
done;
unset file

# Setup pyenv if found
if command -v pyenv > /dev/null 2>&1; then
	eval "$(pyenv init -)"
fi

# Set up fzf if found
if command -v fzf > /dev/null 2>&1; then
  source <(fzf --zsh)
  export FZF_DEFAULT_OPTS="--layout=reverse --border=bold --border=rounded --margin=3% --color=dark"
  source $DOTFILES/scripts/fzf-git.sh
fi

# Activate autosuggestions
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Setup zoxide if found
if command -v zoxide > /dev/null 2>&1; then
  eval "$(zoxide init --cmd cd zsh)"
fi

# Open a tmux session by default
if command -v tmux >/dev/null 2>&1; then
  # If not already inside a tmux session
  if [ -z "$TMUX" ]; then
    # Try to attach to an existing session named 'default'
    tmux attach-session -t default || tmux new-session -s default
  fi
fi

# Check that the function `starship_zle-keymap-select()` is defined.
# xref: https://github.com/starship/starship/issues/3418
if [[ "${widgets[zle-keymap-select]#user:}" == "starship_zle-keymap-select" || \
      "${widgets[zle-keymap-select]#user:}" == "starship_zle-keymap-select-wrapped" ]]; then
    zle -N zle-keymap-select "";
fi

eval "$(starship init zsh)"
